services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_SERVER_AUTHN_CREDENTIALS=${CHROMA_TOKEN}
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.token_authn.TokenAuthenticationServerProvider

volumes:
  chromadb_data:
